uint8 brake # 브레이크
uint8 alarm # 서보알람
uint8 ready # 서보레디
uint8 zspd # 영속도 도달 완료
uint8 inpos1 # 위치 도달 완료 1(0x2401, 0x2402참고)
uint8 tlmt # 토크제한
uint8 vlmt # 속도제한(0x230D, 0x230E참고)
uint8 inspd # 속도 도달 완료(0x2406참고)
uint8 warn # 서보경고
uint8 tgon # 회전검출(0x2405참고)
uint8 reserved1
uint8 reserved2
uint8 reserved3
uint8 reserved4
uint8 reserved5
uint8 reserved6
uint8 org # 원점운전 완료
uint8 eos # 인덱스운전 완료
uint8 iout0 # 인덱스 출력 0
uint8 iout1 # 인덱스 출력 1
uint8 iout2 # 인덱스 출력 2
uint8 iout3 # 인덱스 출력 3
uint8 iout4 # 인덱스 출력 4
uint8 iout5 # 인덱스 출력 5
uint8 reserved7
uint8 reserved8
uint8 reserved9
uint8 reserved10
uint8 reserved11
uint8 reserved12
uint8 reserved13
uint8 reserved14