# axis 허용값
# "x", "y", "z"
string axis
# 이동할 값 (m)
float64 position
# 이동속도 (m/s)
float64 speed
# 가속도 (m/s^2)
float64 acc
# 감속도 (m/s^2)
float64 dec
---
# 서비스에 대한 결과값
# 정상적이면 1 리턴
# 에러시 -1 리턴
int32 success